server:
  port: 8002
spring:
  application:
    name: product-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: product-cus
    api-b:
      path: /api-b/**
      serviceId: manger-cus


