server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: product-pro

  datasource:
    url: jdbc:mysql://localhost:3306/shipy?serverTimezone=GMT%2B8
    username: root
    password: shipy@admin123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    jedis:
      pool:
        max-idle: 10
        max-wait: -1
        max-active: 1000
        min-idle: 2
    timeout: 2000

mybatis:
  mapper-locations: classpath:mapping/*.xml




